/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from './common';

export interface LSP1GraveForwarderInterface extends Interface {
  getFunction(
    nameOrSignature:
      | 'VERSION'
      | 'addTokenToAllowlist'
      | 'getAddressStatus'
      | 'getGrave'
      | 'graveUserCounter'
      | 'graveVaults'
      | 'lsp7RedirectedCounter'
      | 'lsp8RedirectedCounter'
      | 'removeTokenFromAllowlist'
      | 'setGrave'
      | 'supportsInterface'
      | 'tokenAllowlist'
      | 'universalReceiverDelegate'
  ): FunctionFragment;

  encodeFunctionData(functionFragment: 'VERSION', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'addTokenToAllowlist',
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: 'getAddressStatus',
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: 'getGrave', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'graveUserCounter',
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: 'graveVaults',
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: 'lsp7RedirectedCounter',
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: 'lsp8RedirectedCounter',
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: 'removeTokenFromAllowlist',
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: 'setGrave',
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: 'supportsInterface',
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: 'tokenAllowlist',
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: 'universalReceiverDelegate',
    values: [AddressLike, BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: 'VERSION', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'addTokenToAllowlist',
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: 'getAddressStatus',
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: 'getGrave', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'graveUserCounter',
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: 'graveVaults',
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: 'lsp7RedirectedCounter',
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: 'lsp8RedirectedCounter',
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: 'removeTokenFromAllowlist',
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: 'setGrave', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'supportsInterface',
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: 'tokenAllowlist',
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: 'universalReceiverDelegate',
    data: BytesLike
  ): Result;
}

export interface LSP1GraveForwarder extends BaseContract {
  connect(runner?: ContractRunner | null): LSP1GraveForwarder;
  waitForDeployment(): Promise<this>;

  interface: LSP1GraveForwarderInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  VERSION: TypedContractMethod<[], [string], 'view'>;

  addTokenToAllowlist: TypedContractMethod<
    [token: AddressLike],
    [void],
    'nonpayable'
  >;

  getAddressStatus: TypedContractMethod<
    [token: AddressLike],
    [boolean],
    'view'
  >;

  getGrave: TypedContractMethod<[], [string], 'view'>;

  graveUserCounter: TypedContractMethod<[], [bigint], 'view'>;

  graveVaults: TypedContractMethod<[arg0: AddressLike], [string], 'view'>;

  lsp7RedirectedCounter: TypedContractMethod<[], [bigint], 'view'>;

  lsp8RedirectedCounter: TypedContractMethod<[], [bigint], 'view'>;

  removeTokenFromAllowlist: TypedContractMethod<
    [token: AddressLike],
    [void],
    'nonpayable'
  >;

  setGrave: TypedContractMethod<[grave: AddressLike], [void], 'nonpayable'>;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    'view'
  >;

  tokenAllowlist: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    'view'
  >;

  universalReceiverDelegate: TypedContractMethod<
    [
      notifier: AddressLike,
      value: BigNumberish,
      typeId: BytesLike,
      data: BytesLike,
    ],
    [string],
    'nonpayable'
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: 'VERSION'
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'addTokenToAllowlist'
  ): TypedContractMethod<[token: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'getAddressStatus'
  ): TypedContractMethod<[token: AddressLike], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'getGrave'
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'graveUserCounter'
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'graveVaults'
  ): TypedContractMethod<[arg0: AddressLike], [string], 'view'>;
  getFunction(
    nameOrSignature: 'lsp7RedirectedCounter'
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'lsp8RedirectedCounter'
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'removeTokenFromAllowlist'
  ): TypedContractMethod<[token: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'setGrave'
  ): TypedContractMethod<[grave: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'supportsInterface'
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'tokenAllowlist'
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    'view'
  >;
  getFunction(
    nameOrSignature: 'universalReceiverDelegate'
  ): TypedContractMethod<
    [
      notifier: AddressLike,
      value: BigNumberish,
      typeId: BytesLike,
      data: BytesLike,
    ],
    [string],
    'nonpayable'
  >;

  filters: {};
}
